### ISSUE TITLE
Bare metal guide

### ISSUE THREAD

**Issue by maedoc** [talos-systems/talos#1211]
A few things are wrong with the bare metal guide:

First, trivial, the link to edit the docs page is dead https://github.com/talos-systems/talos/edit/master/docs/content/guides/bare_metal.md

More substantially, the docs show using `osctl` command to generate config files and then recommends using matchbox, but no mention of what those config files are, where to put them, how they are supposed to result in a running machine, etc. Are they configs for ignition or something other tech related to coreos?

I regularly boot serves with PXE, have used matchbox and couldn't make heads or tails here.  I'm really trying to build a "minitalos" in vagrant or similar. The docker start is neat but I have bare metal servers to model, test and & run before deploying something 😅

**Comment by maedoc** [comment]
I see the releases have vmlinuz & initrd images, so IIUC, those should be provided by TFTP/PXE boot server with the boot arg `talos.autonomy.io/userdata=http://boot-server/master-1.yaml`?

I'm starting to see how a PoC w/ dnsmasq, pxelinux and talos might work..

**Comment by Ulexus** [comment]
The generated files are the master and worker userdata yamls:  `master-1.yaml`, `master-2.yaml`, `master-3.yaml`, `worker.yaml`.  They are _very_ roughly equivalent to ignition or machine configs.  However, the system really is quite static (as opposed to CoreOS, for instance), so they are more runtime configs than buildtime configs.

That said, the critical thing for the PXE server is to specify the `talos.userdata` kernel cmdline flag to point to the URL from which the node's userdata may be obtained.  This is why the docs mention matchbox, since it comes bundled with a web server which can supply these userdata files, potentially templated and referenced to the individual nodes.

I have been using [DRP](https://rebar.digital/) as a replacement for matchbox (it is more self-contained and simpler to set up and use than matchbox), but I have created talos clusters with both.

We have had a lot of changes recently, so the docs likely still have some holes.  If you join the slack, I'm happy to help.  Running through another first time will definitely help finding those holes.

**Comment by maedoc** [comment]
DRP looks cool.  I'll still try with dnsmasq+ipmitool first since I already have that in place, and try to boot the Talos release via PXE.  I'll get on the Slack later if/when I run into problems, thanks!

**Comment by maedoc** [comment]
to answer my own question, I pulled the vmlinuz & initramfs files from the GitHub release, put them in the tftp/ folder, chmod 555, and added an entry to the appropriate pxelinux file like so
```
LABEL talos
  kernel talos/vmlinuz
  append initrd=talos/initramfs ip=10.11.6.202::10.11.6.1:255.255.255.0:h2:em1:off talos.userdata=http://10.11.6.201:4222/master-1.yaml
```
I guess bare metal pretty varied so it makes sense the docs don't cover the breadth of possibilities.

**Comment by bradbeam** [comment]
If it helps as a point of reference, we do have a quick little kvm script -- https://github.com/talos-systems/talos/blob/master/hack/dev/qemu-boot.sh . It's primarily been used to testing the early boot portions of a single Talos node, but might provide some additional insight.

We do also use matchbox internally, here's a copy of the default profile:

```
{
  "id": "default",
  "name": "default",
  "boot": {
    "kernel": "/assets/talos/nightly/vmlinuz",
    "initrd": ["/assets/talos/nightly/initramfs.xz"],
    "args": [
      "initrd=initramfs.xz",
      "page_poison=1", 
      "slab_nomerge", 
      "pti=on", 
      "random.trust_cpu=on", 
      "console=tty0", 
      "console=ttyS1,115200n8", 
      "printk.devkmsg=on", 
      "talos.platform=packet", 
      "talos.userdata=none"
    ]
  }
}
```
You'll probably need to adjust the console settings, platform, and user data settings.

**Comment by tgerla** [comment]
Hi @maedoc! Thanks for catching the broken edit link. It's been fixed on the live site. Let us know if you run into any other problems!

**Comment by andrewrynhard** [comment]
@maedoc If/when you make progress here, I'd be curious to hear your initial impressions. UX is big for us so any feedback would be greatly appreciated.

**Comment by maedoc** [comment]
Thanks for the help! I used some of the kernel params mentioned above, along with `ip=dhcp talos.userdata=http://..../master-1.yaml` but never see a message from the http server that the yaml config is `GET`ing.  I see a `... timed out!` message, a few more NIC messages and then reboot 😅 

I'll try this out in a VM first..

**Comment by andrewrynhard** [comment]
Interesting. Have you tried without `ip=dhcp`?

**Comment by andrewrynhard** [comment]
This actually sounds like a driver issue. @maedoc Can you share a little more about you hardware, and I can see if we have the required drivers?

**Comment by maedoc** [comment]
> Have you tried without ip=dhcp?

I did, 

> have the required drivers?

This is a Dell R510, dual Xeon, 6 NICs, here's the [output of `lspci`](https://gist.github.com/maedoc/c10a8e3651e110474d1cedb40b1263f6).  The SoL on the BMC has never worked (or I never understood how to get it going), so I've not been able to capture the boot messages, but while the NICs show UP state, I don't see anything suggesting it reacquires the IP address.  I did try `ip=10.11.6.202:etc etc` to provide the kernel a static address, but that didn't seem to work.  I assumed DHCP would Just Work since that's what matchbox uses, but maybe the multiple NICs is a problem?

I've had success with CentOS 7 & OpenSuse, but then again, they are designed for this sort of hardware, so missing driver could be it. I added the output of `lsmod` to the gist linked above.

**Comment by Ulexus** [comment]
So there are a few things potentially here.  I had to extend the DHCP timeout time, because the link wasn't stabilizing in time.  I later figured out that the problem was _actually_ with my switch: I didn't have the port configured as a leaf node for STP ("portfast" in Cisco parlance).

The other is that unless you tell it otherwise, Talos will attempt to get DHCP from _each_ of those network cards in series, regardless of link state, which may take quite a while.  There is now an "ignore" option in the interface spec, to tell DHCP to skip that interface.  For example:

```yaml
machine:
  network:
    hostname: HOSTNAME
    interfaces:
      - interface: eth0
        cidr: MAINIP
        dhcp: false
      - interface: eth1
        ignore: true
```

Finally, without some way to monitor the console, you may very will be missing whatever the _actual_ error is.  SoL is pretty indispensable for this.  I don't know anything about Dell boxes, but for Supermicro, I had to explicitly declare the privilege level to get ipmiutil to work reliably for SoL:

```
ipmiutil sol -a -U bmcUsername -r -P bmcPassword -N bmcIPAddress -V 4
```

**Comment by Ulexus** [comment]
It does look like Dell uses another encryption variant:  https://www.dell.com/support/manuals/us/en/04/idrac8-with-lc-v2.05.05.05/idrac8_2.05.05.05_ug-v1/sol-using-ipmi-protocol?guid=guid-a0398212-10dc-4377-8e63-1e26d8acdae6&lang=en-us

**Comment by maedoc** [comment]
> There is now an "ignore" option in the interface spec, to tell DHCP to skip that interface

That'd be good but how does Talos' kernel get that spec if it can't get an IP address in the first place?

> ipmiutil sol

Thanks for the tip, I tried with ipmiutil, but I see the same behavior as with ipmitool, the SoL session starts but prints nothing.  I've gone into the BIOS to activate SoL but never seems to work.  The iDRAC (Dell BMC) is pretty flaky on these older servers. 

> SoL is pretty indispensable for this
> Dell uses another encryption variant:

Thanks for the link; I tried ipmitool as shown in the article.  Fortunately, I have physical access to the server.

I would suggest closing this issue, since it looks more like a hardware specific thing, not really a Talos issue. I'll keep poking at it and write back when it's working.

**Comment by bradbeam** [comment]
> That'd be good but how does Talos' kernel get that spec if it can't get an IP address in the first place?

The workflow around the networking setup / configuration goes something like:

- ... ( other stuff )
- basic networking configured
  - DHCP request out all interfaces, configure interfaces based on response
- download userdata
- ...
- start networkd
  - configure networking based on userdata if anything is specified. otherwise, go through the dhcp process again and set up a watcher to renew the address lease periodically.

**Comment by Ulexus** [comment]
PXE-booted Linux boxes generally always go through a two-step DHCP process: once from the kernel, and once from userspace.  Talos actually goes through a _three_ step process during installation: once for the kernel, once from the bootstrap, and once from the final system.  The kernel DHCP driver checks for carrier, if available.  The Talos once does not.

SoL _also_ requires support from both the BIOS (telling it to send console output to the SoL serial port) and the OS (telling _it_ to send console output to the SoL serial port).  It could also be a flaky BMC, of course... just covering the bases.

The difficulty in trying to capture logs of a failure from the physical console is that there is often not enough time to _see_ the final error before the system reboots.  SoL avoids this by retaining the scrollback buffer of the terminal.

**Comment by andrewrynhard** [comment]
Would it be worth having a `talos.interface.<name>.ignore=true` option for the kernel phase?

**Comment by maedoc** [comment]
> SoL avoids this by retaining the scrollback buffer of the terminal.

completely totally agree, if only it'd work on this server 🙏  I wasn't counting on BMC support here btw so thanks a bunch for all the helpful details!

> once for the kernel, once from the bootstrap, and once from the final system

So I should see three `DHCPDISCOVER`s in my logs from the right MAC address, I guess.  I'll have to dig in a little more

> Would it be worth having a `talos.interface.<name>.ignore=true` option for the kernel phase?

I'd have 5.. I thought (perhaps erroneously) that the kernel knows which nic was used for PXE boot.. wouldn't that be easier?  (sorry if this is naive, just brainstorming)

**Comment by Ulexus** [comment]
That wouldn't opt out of the kernel phase; that would opt out of the bootstrap phase.  By the time we start interpreting talos options, the kernel phase has already occurred.

I already added `talos.network.interface.ignore`, which accepts interfaces which should be ignored during the bootstrap phase.

**Comment by andrewrynhard** [comment]
@maedoc If you made any progress here, I'd be happy to hear about any specifics we are missing. We are making a push in v0.3 to have good docs and I'd like to get our bare metal guides up to snuff. Additionally, you may want to take try a newer version of v0.3 alpha Talos. We have made a lot of improvements.

**Comment by andrewrynhard** [comment]
Closing in favor of #1383. We intend on getting that done this week.

**Comment by maedoc** [comment]
@andrewrynhard sorry nope I wasn't able to follow up on this. thanks again for all the feedback.

**Comment by andrewrynhard** [comment]
@maedoc We updated our docs with a simple how to for matchbox. You might also find https://github.com/talos-systems/talos/tree/master/hack/test/integration to be a better guide. Shows an example of the full dnsmasq, matchbox, haproxy and bare metal Talos setup.

**Comment by maedoc** [comment]
@andrewrynhard thanks for the follow up, I will check those out.
