### ISSUE TITLE
Default node should not return 127.0.0.1

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1349]
When not specifying a node, it looks like we set the node metadata in the API response to `127.0.0.1`

```
[I] /t/scratch $ osctl version
Client:
	Tag:         6de32dd
	SHA:         6de32dd
	Built:
	Go version:  go1.13.3
	OS/Arch:     linux/amd64

Server:
	NODE:        127.0.0.1
	Tag:         6de32dd
	SHA:         6de32dd
	Built:
	Go version:  go1.13.3
	OS/Arch:     linux/amd64
```

 This is very confusing. We should use the IP of the node.

**Comment by bradbeam** [comment]
i _think_ this is only shown in docker setups since talos config points to 127.0.0.1

Specific bits of code i think are responsible for this:
https://github.com/talos-systems/protoc-gen-proxy/blob/master/pkg/proxy/proxy.go#L85-L90 // https://github.com/talos-systems/talos/blob/master/api/api.pb.go#L292-L298

im not sure which is the right/best approach. we could change that logic to `s/md[:authority]/hostaddr/`, but that means if someone were to hit a load balancer or dns name, we'd always replace it with the hosts ip address. we could flex on only the loopback addr i guess?
