### ISSUE TITLE
Explore ways to handle entirely static network configuration

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#1453]
The current bootup/networkd implementation follows the pattern of:

```
- DHCP all interfaces
- Hope we get an address
- Attempt to download userdata
```

This works on most cloud providers, but for on prem situations, dhcp may not be an option at all. We should figure out some ways/methods/etc to work around this.

Only thought that comes to mind: 

- kernel args -- while this is probably the 'simplest' to add on, it gets complex quickly. We'd need to expose not only the addressing configuration but routing as well. I'm concerned we'd end up with a whole hodge podge of json.. ex,  `talos.network = '{ device: eth0, cidr: 10.0.0.2, routes: [ { src: x, dst: y }, ... ] }'`

**Comment by andrewrynhard** [comment]
@Ulexus Pinging you here just in case you have thought about this before, and I know it may apply to you.

**Comment by Ulexus** [comment]
We do have mechanisms for disabling DHCP now.  It just has to be declared for _each_ network interface in both the kernel commandline _and_ the talos config yaml.  It works, but the user experience is not great.

Two features which would make for greater convenience:
  - automatic population of the kernel commandline parameters disabling DHCP on installation referenced from the talos network configuration in the YAML (so these don't have to be managed separately by the user)
  - ability to globally disable DHCP on all interfaces (reduce boilerplate for nodes with large numbers of network interfaces)

All of that said, I do agree that the default SHOULD be to have DHCP _enabled_.  I wouldn't want to change that.  It would just be nice to make it more convenient to kill it when appropriate.

**Comment by Ulexus** [comment]
Ah, but I neglected the meat of the problem:  how do you specify the network config in the chicken-and-egg of talos config fetchment over the network.

The JSON-encoded talos.network is not a horrible idea.  I do wonder about the spaces in the parameter, though, such that additionally base64-encoding might be good?

The kernel itself does already have a pretty complete [network configuration](https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt) with `ip=XXX` (including, for instance, DNS and even NTP).  I would definitely rather re-use that than invent something new.  On the other hand, the _intention_ of that option is for configuring minimal networking to bootstrap from NFS (which is why the docs are bundled in with the nfsroot stuff), so there _might_ be some side-effects I don't know about.

It might also be reasonable to implement some sort of connectivity test when talos itself is about to bring up the network system which operates along the lines of: "if we have internet reachability _and_ we have no explicit network configuration, leave the network alone."

**Comment by andrewrynhard** [comment]
Before talos had `networkd` it used the kernel `ip=dhcp` option, and it worked great. I think `ip` is a great idea. Completely forgot about that.

**Comment by bradbeam** [comment]
Yeah forgot about that parameter. I'm game with that. Did some testing and works just like you'd expect:

```
<6>[    1.325702] IP-Config: Complete:
<6>[    1.327080]      device=eth0, hwaddr=00:0c:29:d1:c6:39, ipaddr=10.0.0.99, mask=255.0.0.0, gw=255.255.255.255
<6>[    1.327448]      host=master-1, domain=, nis-domain=(none)
<6>[    1.327818]      bootserver=255.255.255.255, rootserver=255.255.255.255, rootpath=
<6>[    1.327818]      nameserver0=10.0.0.1
```

from adding the following to `image-vmware` target in the makefile. 
```
-e ip=10.0.0.99:::255.0.0.0:master-1:eth0:off:10.0.0.1
```

I'll add a case in the network config if `ip` kernel param detected, don't do anything
