### ISSUE TITLE
docs: component overview & machined links broken [404]

### ISSUE THREAD

**Issue by Nold360** [talos-systems/talos#2117]
### Description

The relative links to the components on the [machined doc](https://www.talos.dev/docs/v0.5/en/components/machined) & [component overview ](https://www.talos.dev/docs/v0.5/en/components/overview) are boken [404] , sadly i stole the link format from the machined doc.

How should the links be made?

**Comment by andrewrynhard** [comment]
ahh look like we need `/v0.5/en` (e.g. `https://www.talos.dev/docs/v0.5/en/components/apid`)

**Comment by Nold360** [comment]
hmm. but that would mean we need to update the links with every release :/

**Comment by tgerla** [comment]
I think the links need to look like: [containerd](containerd)

I can test it a little later if nobody else gets to it first.

**Comment by andrewrynhard** [comment]
> hmm. but that would mean we need to update the links with every release :/

We sort of already do that today because there is no guarantee that docs should/will be the same between any two releases. That being said, if we can find a better way I am all ears. That might be what @tgerla is talking about. Ahh yeah maybe so... what he is suggesting would make the links relative I think.

**Comment by Nold360** [comment]
That was also my first thought. But then i took the links  from the machined site. I would fix this, but i still havn't got the dev-env running. Of cause the current npm version on buster has a bug i ran into...
