### ISSUE TITLE
Support Config Update API

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#2345]
For configs that have been persisted, there may be a case in which users want to re-pull to update certain values or whatnot. We should support a way to trigger a re-pull regardless of persistence setting.

MVP:
- Validate the received config
- Replace on disk config upon success of validation
- Reboot

**Comment by salkin** [comment]
@Ulexus would option to the command to do a "reset" make sense to you? It would solve the issue with avoiding the need for rebooting twice, when the target is to reset the node with a new config

**Comment by Ulexus** [comment]
@salkin Yes, functionally-speaking.  However, Reset already implies a configuration replacement, so I see this option to be more logically applied to Reset than to ApplyConfiguration.  The idea in that case would be the ability to pass a configuration to be used directly, rather than obtaining one through the normal discovery process.
