### ISSUE TITLE
Publish official AWS AMIs

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#351]
We should publish AMIs and make them available to the public.

**Comment by unixfox** [comment]
I could manually provide an AMI for `eu-central-1` (that's the region I use the most) but we still need to automate the process to have updated images.
I won't publish an AMI for every AWS region because it would a bit too expensive for me.
While we are at it could there be a way to have free AMI hosting due to the fact that talos is open source? I didn't see anything like that on Google but I read that Nonprofits organizations can have free credits: https://aws.amazon.com/government-education/nonprofits/

**Comment by andrewrynhard** [comment]
The nonprofit is an interesting idea. As for the short term. We have an AWS account we can start publishing AMIs to. My main concern for now is figuring out how to integrate this with the CI. I wouldn't put the burden of hosting the AMIs on you :).

**Comment by andrewrynhard** [comment]
I wish we could do a poll on which regions to support.

**Comment by andrewrynhard** [comment]
This is now part of the `Makefile` and will be ran manually (just like the GCE image) on releases. We will worry about automating later. Closed by #602.
