### ISSUE TITLE
Feature Request: Hardware Monitor for Raspberry Pi POE Hat in rpi_metal build

### ISSUE THREAD

**Issue by mhwilkes** [talos-systems/talos#4491]
## Feature Request
Hardware Monitor for Raspberry Pi POE Hat

### Description
When running in a cluster, the raspberry pi 4 POE hat does not spin. I believe this is because of the absence of a hardware monitor kernel driver for the raspberry pi like [here](https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/hwmon/rpi-poe-fan.c)

I am not sure if this would be something that the team would want to implement for the Raspberry Pi Image but it would be beneficial to running pi clusters using talos.

If this isn't something that would be considered to implement, possibly making it an optional kernel param?

Looking forward to feedback

**Comment by ryanjafari** [comment]
Yeah I'm also facing this

**Comment by smira** [comment]
Is that already in upstream Linux kernel?

**Comment by frezbo** [comment]
we need to set this https://github.com/talos-systems/pkgs/blob/master/kernel/kernel/config-arm64#L7353, I believe

**Comment by ryanjafari** [comment]
I believe it is yeah

**Comment by ryanjafari** [comment]
Oh ok I was thinking of building an image for myself with the support but it seems it just needs to be turned on via a param? In theory?

**Comment by smira** [comment]
I can throw a PR for it, and we'll get a new kernel with 0.14.0-beta.0 release next week.

**Comment by ryanjafari** [comment]
thank you @smira!!

**Comment by mhwilkes** [comment]
Big thanks @smira !!

**Comment by ryanjafari** [comment]
Hey @smira I'm running the pre-release fresh v0.14.0-beta.0 and the RPI4 Model B PoE hat fans still aren't spinning up. No emergency, I'm probably doing something wrong, just noting it here. Let me know if you have any ideas for what I can try.

**Comment by ryanjafari** [comment]
It's also possible the config hasn't been merged in yet :-)

**Comment by smira** [comment]
@ryanjafari I'm pretty sure that the config should be there, you can check it with

`talosctl -n <IP> read /proc/config.gz | zgrep CONFIG_PWM_RASPBERRYPI_POE`

But I don't have the hardware to test it with

**Comment by ryanjafari** [comment]
Thanks @smira I'll test in a bit

**Comment by frezbo** [comment]
@ryanjafari you also need to add the extra overlays. I'll test over the weekend and let you know if that works

**Comment by frezbo** [comment]
https://raspberrypi.stackexchange.com/questions/118863/how-can-i-enable-the-fan-on-the-official-poe-hat-under-fedora outline the steps needed to get this working. TLDR we need a custom device tree patch

**Comment by frezbo** [comment]
@ryanjafari if you use the firmware files from `boot` folder from the `next` branch of raspbeerypi/firmware repo PoE fan works. The serial console seems to be [broken](https://github.com/raspberrypi/firmware/issues/1682) with `next` branch of firmware.

**Comment by ryanjafari** [comment]
Hey @frezbo thanks for following up on this. As it turns out, I'm still struggling.

My feeling is I'm not understanding something, and that I need to somehow edit the `metal-rpi_4-arm64.img` image to use the `next` firmware files. Or build the image from scratch (which I'm also unsure how to do).

I studied your resources and tried:

1. Updating the RPI's firmware to the `next` branch using `sudo BRANCH=next rpi-update` on Raspi OS (revision: `6f48...fb57`)
2. Make sure the bootloader is at latest `stable`, again using Raspi OS

Then after realizing the bootloader must be using files present on the Talos image...

1. Replacing the files in the `EFI` partition 1 after mounting it from `metal-rpi_4-arm64.img`. Of course, I get something like `bad cluster size: 0` on boot.
2. Using `mount -o loop` to edit the `metal-rpi_4-arm64.img` image in place, and shift everything into additional space. I ran into some trouble with this as well.

Would you be so kind as to point me in the right direction? Maybe there is something much easier I'm missing. Anything at all would be appreciated.

Thanks to you and the team,
Ryan

**Comment by ryanjafari** [comment]
Perhaps I am making some progress. I seem to have all the files from `firmware/next` over, but still no PoE fan. I'm trying to work with `config.txt` now to see what I need to tweak there...

**Comment by frezbo** [comment]
@ryanjafari apologies if my comment didn't help. I'll provide some steps in details:

Follow the Talos Raspberry Pi docs on writing the image to the SD card (I will assume the card is named `/dev/mmcblk0`, else update in the following commands)

Once the Talos image is written to the SD card follow these steps:

```bash
mkdir -p /tmp/mnt
sudo mount /dev/mmcblk0p1 /tmp/mnt
sudo cp -r <path to next firmware>/boot/* /tmp/mnt/
sudo umount /tmp/mnt
sudo sync
```

Now pop out the SD card and boot the Pi. `confix.txt` needs no changes. I tested this on v0.14 of the Talos release.

**Comment by ryanjafari** [comment]
Hi @frezbo - thanks so much for the instructions. I'm happy to report it works. All four of my PoE hats' fans are running :-)

P.S. in my adventures I found the RPI docs may need updating - shall I just raise an issue? Happy to help propose edits.

**Comment by frezbo** [comment]
@ryanjafari cool, yes let us know what's missing and will update. Please create an issue

**Comment by frezbo** [comment]
@ryanjafari the next talos release should have the PoE hat support by default https://github.com/siderolabs/talos/pull/5349

**Comment by ryanjafari** [comment]
You are AWESOME for following up on this thank you.

Especially since my hats stopped working on a recent upgrade. :)

**Comment by frezbo** [comment]
now upgrades should work fine since it has the right firmware

**Comment by ryanjafari** [comment]
Hey there @frezbo - so far I haven't seen the fans working - I've been running v1.0.3 on each of my four RPIs for a while now. Actually, two of them have now mysteriously been "dying" periodically for no apparent reason - they become unavailable on the network and show taints of: `node.kubernetes.io/unreachable:NoSchedule` and `node.kubernetes.io/unreachable:NoExecute`.

I've tried updating bootloader firmware, trying different ports, cables, restarting etc. It seems after a while of working just fine after a few days they just die. I'm not for certain on anything at this point but I'm wondering if it's due to heat because the weather in NY is now changing to spring.

I'm going to try upgrading to v1.0.4 now on my four RPIs to see if that helps anything.

Anyway, just keeping this thread up-to-date w/ my latest experiences.

**Comment by frezbo** [comment]
this is only supported in the `1.1.x` releases, so you.d have to pick the latest from master

**Comment by frezbo** [comment]
@ryanjafari  `v1.1.0-alpha.1` has the support, so upgrading to that should enable the fan

**Comment by ryanjafari** [comment]
Oh oh gotcha! Thanks!

**Comment by ryanjafari** [comment]
Thanks @frezbo I confirm it works and they spin at a speed that keeps them quiet.

**Comment by frezbo** [comment]
cool, the defaults are pretty good from what I've observed. I don't have heavy workloads though

![image](https://user-images.githubusercontent.com/18496730/167613901-90ac998f-9f7c-4144-8230-9ec044c13ebc.png)
